### PR TITLE
Fix tm-bench metrics

### LINKED ISSUE #101: [tm-bench] Incorrectly computes metrics
For one, we use the `BlockchainInfo` rpc call which returns max 20 blocks at a time, so we need to check that and keep querying if there are more blocks.

Also we could be more clear about the computation: just we know how many txs are sent, we should find the first block with a tx and keep grabbing blocks until we've committed enough txs, then look at the timestamp difference between that first and last block.

I started some WIP fixes here: https://github.com/tendermint/tools/pull/100

### PR DESCRIPTION
**Pull request by ebuchman**
Closes #101

### CODE REVIEW

File: tm-bench/main.go [hunk 1]
```diff
@@ -132,6 +132,22 @@ func calculateStatistics(client tmrpc.Client, minHeight int64, timeStart, timeSt
 		os.Exit(1)
 	}
 
+	maxHeight := info.LastHeight
```
Comment (melekes) [inline tm-bench/main.go]: `lastHeight`

File: tm-bench/transacter.go [hunk 2]
```diff
@@ -176,9 +176,6 @@ func (t *transacter) sendLoop(connIndex int) {
 			}
 
 			timeToSend := time.Now().Sub(startTime)
-			if timeToSend < 1*time.Second {
```
Comment (melekes) [inline tm-bench/transacter.go]: m?

File: tm-bench/main.go [hunk 3]
```diff
@@ -132,6 +132,22 @@ func calculateStatistics(client tmrpc.Client, minHeight int64, timeStart, timeSt
...
+	diff := maxHeight - minHeight
+
+	blockMetas := info.BlockMetas
+	offset := len(blockMetas)
+	for len(blockMetas) < int(diff) {
+		// get blocks between minHeight and last height
+		info, err := client.BlockchainInfo(minHeight+int64(offset), 0)
```
Comment (ValarDragon) [inline tm-bench/main.go]: Interestingly, this returns (last block - 20 to last block), not (first block to first block + 20). This logic assumes the latter.

File: tm-bench/main.go [hunk 4]
```diff
@@ -156,29 +160,23 @@ func calculateStatistics(client tmrpc.Client, minHeight int64, timeStart, timeSt
...
 		// check if block was created before timeStop
 		if blockMeta.Header.Time.After(timeStop) {
-			break
+			continue
 		}
-
 		sec := secondsSinceTimeStart(timeStart, blockMeta.Header.Time)
 
 		// increase number of blocks for that second
-		if _, ok := numBlocksPerSec[sec]; !ok {
```
Comment (ValarDragon) [inline tm-bench/main.go]: This check isn't needed, since its already been initialized to zero.

File: tm-bench/main.go [hunk 5]
```diff
@@ -119,19 +120,38 @@ func latestBlockHeight(client tmrpc.Client) int64 {
...
 	}
 
+	lastHeight := info.LastHeight
+	diff := lastHeight - minHeight
+
+	blockMetas := info.BlockMetas
+	offset := len(blockMetas)
+	for len(blockMetas) < int(diff) {
+		// get blocks between minHeight and last height
+		info, err := client.BlockchainInfo(minHeight, lastHeight-int64(offset))
```
Comment (ebuchman) [inline tm-bench/main.go]: don't we need to progress the minHeight forward as well ?

Comment (ValarDragon) [reply tm-bench/main.go]: I don't think we have to, since the block at the minheight isn't getting returned until lastHeight is within 20 blocks of minHeight. I'll test a couple more times to ensure that its printing fully in order though.

Comment (ebuchman) [reply tm-bench/main.go]: oh I see, it counts down from the maxHeight parameter
